# Generated by Django 4.0.6 on 2022-07-22 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_remove_listing_id_alter_listing_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPlayer',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('country', models.CharField(max_length=30)),
                ('fargo', models.IntegerField()),
                ('current_year_earnings', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
    ]
