# Generated by Django 4.0.6 on 2022-07-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='article',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
