# Generated by Django 4.0.6 on 2022-07-15 22:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, unique=True),
        ),
    ]
