# Generated by Django 4.0.6 on 2022-07-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_alter_listing_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(default='Pool Tournament', max_length=50),
        ),
    ]
